### ISSUE TITLE
CometBFT tracker

### ISSUE THREAD

**Issue by namn-grg** [GeoDecConsensus/geodec#4]
- [ ] Implement install scripts
- [ ] Implement CometBFT run scripts
- [ ] Write and get testnet logs
- [ ] Read the logs to benchmark
- [ ] Get client running and send transactions
- [ ] Benchmark e2e latency and throughput
- [ ] Benchmark consensus
